### ISSUE TITLE
Option to not generate references

### ISSUE THREAD

**Issue by khiemlam** [reifyhealth/specmonstah#13]
There are cases where I do not want to generate reference ids for certain entities, especially if these reference ids are optional.

For example, if a publisher has an address and that address is optional reference id, I would like to generate a publisher and be able to define nil for the address.  In this case, I would expect that an address entity would not be created.  However, as it currently implemented in specmonstah, the publisher's address will be set to nil, but a dummy, dangling address would still be created.

**Comment by flyingmachine** [comment]
closing this as it's covered in specmonstah 2
