### ISSUE TITLE
query is invalid — I’m doing something wrong?

### ISSUE THREAD

**Issue by aviflax** [reifyhealth/specmonstah#28]
Hi, I hope you don’t mind me posted what’s essentially a support request via this channel — feel free to close this without comment if this isn’t a good time or place.

I’m trying out the latest commit (bb1ccd083d60) on the `v2-graph` branch, which seems like it might be the basis of your upcoming 2.0 release, and I’m having some trouble with my schema.

My schema, which may be slightly insane, is:

```clojure
(def schema
  {:user        {:prefix    :u}
   :system      {:prefix    :s
                 :relations {:used-by-system-id [:system :id]
                             :used-by-user-id   [:user :id]}}
   :container   {:prefix    :c
                 :relations {:part-of-system-id [:system :id]
                             :used-by-system-id [:system :id]
                             :used-by-user-id   [:user :id]}}})
```

What I’m trying to express there is that:

* a system is (optionally) used by another system
* a system is (optionally) used by a user
* a container is part of a system (although not all systems must have containers)
* a container is (optionally) used by a (different) system
* a container is (optionally) used by a user

Sorry for all the (optionally) — that’s not actually in the schema because I don’t know how/whether to specify it.

Are these relationships feasible with this library?

When I run this:

```clojure
(sm/build-ent-db {:schema schema} {:container [1]})
```

I get this exception:

<details>
<summary>ExceptionInfo query is invalid</summary>

With this data attached to the exception:

```clojure
#:clojure.spec.alpha{:explain-data
                     #:clojure.spec.alpha{:problems
                                          ({:path [1 :n-1],
                                            :pred
                                            (clojure.core/fn
                                             [%]
                                             (clojure.core/or
                                              (clojure.core/nil? %)
                                              (clojure.core/sequential?
                                               %))),
                                            :val 1,
                                            :via
                                            [:reifyhealth.specmonstah.core/query
                                             :reifyhealth.specmonstah.core/query-term],
                                            :in [:container 1 0]}
                                           {:path [1 :n-2],
                                            :pred
                                            (clojure.core/fn
                                             [%]
                                             (clojure.core/or
                                              (clojure.core/nil? %)
                                              (clojure.core/sequential?
                                               %))),
                                            :val 1,
                                            :via
                                            [:reifyhealth.specmonstah.core/query
                                             :reifyhealth.specmonstah.core/query-term],
                                            :in [:container 1 0]}),
                                          :spec
                                          :reifyhealth.specmonstah.core/query,
                                          :value {:container [1]}}}
```

</details>

Any help or feedback would be appreciated! Thank you!

**Comment by flyingmachine** [comment]
hi avi! I haven't tried locally but I think your query needs to be `{:container [[1]]}`, so hopefully this should do it:

```clojure
(sm/build-ent-db {:schema schema} {:container [[1]]})
```

**Comment by aviflax** [comment]
Thanks Daniel! That worked. In the meantime I’ve found [an alternate path](https://github.com/FundingCircle/fc4c/pull/51/files#diff-f12837d1aefdc13707bfbec0a4c47e23R131) to constructing valid related entities for my library — it’s not nearly as sophisticated as that of Specmonstah, but tbh that might be a bit too sophisticated and/or bleeding edge for me right now anyway.

Good luck with the library, I’ll be keeping an eye on it!
