### ISSUE TITLE
rename to "specmonster"?

### ISSUE THREAD

**Issue by flyingmachine** [reifyhealth/specmonstah#33]
On hearing "specmonstah", a person is less likely to google "specmonstah" than they are to google "specmonster." I've encountered this once already, and as much as I want to honor its Boston roots I think it'd be a shame for the library to be difficult to find because of an inside joke :)

**Comment by flyingmachine** [comment]
@codonnell-reify would love your thoughts on this

**Comment by codonnell-reify** [comment]
I don't have any objections, personally. I couldn't even find it googling "clojure specmonster," which is pretty disappointing.

**Comment by cldwalker** [comment]
I don't know. Opening this issue seems to have mostly solved this ;)

![image](https://user-images.githubusercontent.com/11994/43529691-d68bc5c0-9579-11e8-92c5-ff163ef1c457.png)

@flyingmachine It's totally your call. The name makes laugh but agree that searchability would be helpful. Perhaps to honor its Boston roots we drop some funny monstah link in the readme e.g. FSM

**Comment by flyingmachine** [comment]
that's actually a good compromise. why don't we create a "specmonster" project and have it point to "specmonstah"? I'm going to do a bit more README work and then proceed with an alpha release :)

**Comment by flyingmachine** [comment]
We could also update the README to say something like, "Specmonstah, (Boston for 'specmonster')"

**Comment by danielcompton** [comment]
Looks like this discussion has been ingested by the Google Brain:

<img width="738" alt="screenshot of google chrome 4-09-18 10-10-33 am" src="https://user-images.githubusercontent.com/811954/45002456-c4b34c80-b02a-11e8-8d8a-2953b1235a58.png">

**Comment by flyingmachine** [comment]
We're going forward with "specmonster" and letting google point non-bostonians in the right direction :)
