### ISSUE TITLE
release a snapshot or alpha to clojars

### ISSUE THREAD

**Issue by flyingmachine** [reifyhealth/specmonstah#34]
I'd like to use this on projects without having to manually install it. I think it's stable enough, or at least useful enough, to cut an alpha release.

**Comment by flyingmachine** [comment]
it would be cool to have CI automatically deploy snapshot releases

**Comment by codonnell-reify** [comment]
I agree on both counts. 👍

**Comment by flyingmachine** [comment]
sweet! I think Reify holds the keys to CI?

**Comment by flyingmachine** [comment]
I suppose we could go ahead and merge v2-graph into master, and I believe circle is already set up to deploy. if that's cool with you i think we should do it

**Comment by cldwalker** [comment]
👍on alpha and merge. Before making 2.0.0 we'll want to get bengal converted per https://github.com/reifyhealth/specmonstah/issues/26
