### ISSUE TITLE
combining `{:refs {:x ::sm/omit}}` and `{:spec-gen {:x nil}}` does not work

### ISSUE THREAD

**Issue by flyingmachine** [reifyhealth/specmonstah#36]
:x should be present and nil. instead it's absent.

Example query:

```clojure
(sg/ent-db-spec-gen-attr {:schema schema}
                         {:todo-list [[1 {:refs     {:owner-id ::sm/omit}
                                          :spec-gen {:owner-id nil}}]]})
```

**Comment by manderson202** [comment]
Just saw this. The problem is deciding which takes precedence: the "omit" or the spec-gen. Perhaps this should be a query compile error since intent is ambiguous?

**Comment by flyingmachine** [comment]
I think whatever you pass to `:spec-gen` in the query should take precedence. `:refs {:owner-id ::sm/omit}` applies to building the ent db, and visiting functions' default behavior should respect whatever's in the ent db. The query is meant to specify deviations from the default behavior, so whatever's in the `:spec-gen` part of the query should take precedence over whatever has resulted from default behavior up to that point.

**Comment by flyingmachine** [comment]
Hmmm I must have been mistaken about this, I can't repro it
