### ISSUE TITLE
names also for the queried entities

### ISSUE THREAD

**Issue by Knotschi** [reifyhealth/specmonstah#4]
Heyhou,
Thanks for this nice library. I am currently writing an integration test where I want to use specmonstah to create my testcases setup and it fits very well my needs.

In my tests I need to have access to the generated ids of my entities. 
Lets say I do:

```
(def result-4 (rs/gen-tree gen1 relations [[::book {:publisher-id :p1}]
                                           [::book {:publisher-id :p2}]
                                           [::book {:publisher-id :p3}]]))
```

With the result of this, I can easily find the ids from the publisher :p1 with 
`(-> result-4 ::publisher :p1 :id)`
This is very useful to access properties of my entities.
Unfortunately I can not directly access the id of the second book.
I need to assume that the result vector has the same ordering than my query to get the id from the last book.  (`(-> result-4 ::rs/query ::book last)`)  - not sure if this is a good idea

I would prefer to give them also a name.

something like this would be nice for me:
```
(def result-4 (rs/gen-named-tree gen1 relations {:b1 [::book {:publisher-id :p1}]
                                                 :b2 [::book {:publisher-id :p1}]
                                                 :b3 [::book {:publisher-id :p2}]}))
```

and then I can do `(-> result-4 ::rs/query ::book :b1 :id)` 
or even just `(-> result-4 ::book :b1 :id)`

What do you think about it?

**Comment by flyingmachine** [comment]
closing as the new version of specmonstah incorporates this idea :)
