### ISSUE TITLE
invalid fn spec for core/coll-relation-attr?

### ISSUE THREAD

**Issue by stevebuik** [reifyhealth/specmonstah#42]
If you invoke (clojure.spec.test.alpha/instrument) and then invoke a build with a schema that includes a :relation, it produces a spec error.

I think the error is due to the s/tuple fspec for that fn which should be an s/cat instead.

I'm working on a patch and will submit a PR when ready but I'm using Cursive so boot support is painful. Might not be too quick.

**Comment by flyingmachine** [comment]
This was fixed with #48 . Thanks!
