### ISSUE TITLE
How to establish relation between attributes of different ents

### ISSUE THREAD

**Issue by sushovannits** [reifyhealth/specmonstah#49]
Is there any way we can establish relation between two different entities. 
e.g.: we have two different entities `car`and `wheel`. Now every `wheel` refs to a `car`.
However both `car` and `wheel` has a `price` attribute. The relation I want to establish is:
`price` of `wheel` **w0** which refs `car` **c0** is not greater than **c0**'s price.

Is it possible in specmonstah? I am not sure if insert visitation can be used.

**Comment by flyingmachine** [comment]
Thanks for question! Not sure when I'll be able to look into it, but hopefully in the next couple weeks :)

**Comment by flyingmachine** [comment]
There's no way to directly impose this kind of constraint. I do think it'd be possible to write a visitor that could traverse the ents, get to `w0` and check its price compared to `c0`'s price. [This code](https://github.com/reifyhealth/specmonstah/blob/develop/src/reifyhealth/specmonstah/spec_gen.cljc#L58) shows how you can get referenced ents and their attributes.

**Comment by flyingmachine** [comment]
PS thanks for the good question!
