### ISSUE TITLE
Is a combination of :uniq and :coll allowed in constraints?

### ISSUE THREAD

**Issue by keerts** [reifyhealth/specmonstah#52]
Is a combination of :uniq and :coll allowed in constraints?

Is this something that could work:
```
(def schema2
  {:contact {:prefix      :contact
             :spec        ::contact}
   :company {:prefix :company
             :spec ::company
             :relations   {:employs [:contact :id]}
             :constraints {:employs #{:uniq :coll}}}})
```

It seems it does not force new ents when used with a query like: {:company [[1 {:refs {:employs 2}}]]}

**Comment by flyingmachine** [comment]
I want to look into this a little more, but I'm pretty sure you don't need to `:uniq` if you have `:coll`. Hope this helps!
