### ISSUE TITLE
How to keep relationships when recording to db?

### ISSUE THREAD

**Issue by ignorabilis** [reifyhealth/specmonstah#56]
We're looking at this library since it can alleviate entity generation for each test. After trying to use it though a few things are unclear, with the main one being:
- How can we keep the relations of the entities when recording them to the db? We're using Datomic. Specmonstah generates some ids and based on them you have a relation between ents; however when you transact those ents these relations get lost

Ideally we want to transact all entities in a single tx. Each entity would have a string id, which can be used as tempid by Datomic; then each relation will be kept automatically.

For example:
``` clojure
;; schema
{:person {:prefix :p
               :spec   :sm/person}
 :company {:prefix :co
                   :spec   :sm/company}
 :membership {:prefix    :mem
                        :spec      :sm/membership
                        :relations {:membership/group  [:company :id]
                        :membership/member [:person :id]}}}

;; query 
{:person     [[:p0 {:spec-gen {:person/title "me"}}]]
 :membership [[1 {:refs {:membership/member :p0}}]]}

;; ents result
{:co0 {:company/name "3VxGlbNFWLVW3v7cn4", :id 66},
 :mem0 {:id 2, :membership/group 66, :membership/member 22},
 :p0 {:person/email "W30lkwEo6w-Wx@xW.com",
      :person/first-name "Oe",
      :person/last-name "D4oy8HOU98RR",
      :id 22}}

;; tx (not possible right now)
[{:company/name "3VxGlbNFWLVW3v7cn4", :db/id "66"},
 {:db/id "2", :membership/group "66", :membership/member "22"},
 {:person/email "W30lkwEo6w-Wx@xW.com",
  :person/first-name "Oe",
  :person/last-name "D4oy8HOU98RR",
  :db/id "22"}]
```

Not sure if this is possible in some other way or if I'm missing something - let me know if that's the case!

**Comment by flyingmachine** [comment]
@ignorabilis I'm not sure what the issue is? Is the problem that the id's are ints when you'd like them to be strings? From what I can tell:

* The company's id is 66
* the person's id is 22
* The membership's `membership/group` is 66, corresponding to the company's id
* The membership's `membership/member` is 22, corresponding to the person's id

And that seems right to me?

**Comment by flyingmachine** [comment]
Going to close this as I haven't heard a response, but please feel free to respond if this is still an issue :)
