### ISSUE TITLE
Corner case for default-attr in relation-template

### ISSUE THREAD

**Issue by khiemlam** [reifyhealth/specmonstah#7]
Default-attr in relation-template is only supported for cases where the reference-attr is empty.  If the reference-attr is not empty, then the default-attr does not get applied to the generated entity.

While the default value is applied to the :author-name, it does not work for :book-name.
```
(def default-attr-relation-template
  {::author [{} {:author-name "default"}]
   ::book [{:author-id [::author :id]} {:book-name "My Book"}]})
```

**Comment by flyingmachine** [comment]
this is fixed in specmonstah 2 :) values you supply in the query override values that have been automatically generated
