### ISSUE TITLE
core/add-ents validation idea

### ISSUE THREAD

**Issue by cldwalker** [reifyhealth/specmonstah#70]
Hi @flyingmachine. In our test helper fn that wraps spec-gen/ent-db-spec-gen, which in turn  wraps [core/add-ents](https://github.com/reifyhealth/specmonstah/blob/1e13d718d67a62fbc80b47896eb9cc5b4951c31c/src/reifyhealth/specmonstah/core.cljc#L573), we've added validation to ensure the query doesn't contain any keys/types that don't exist in schema. We've been bitten a couple times where we didn't realize a query contained a nonexistent type. In our case we're at 34 ent types for our schema so perhaps this isn't a common problem for other folks. In any case here's the validation code in case it's helpful:

```clj
   (let [diff (set/difference (set (keys query)) (set (keys schema)))]
     (assert (empty? diff)
             (str "The following keys are not valid specmonstah types: " diff)))
```

Happy to PR if you think it's helpful

**Comment by flyingmachine** [comment]
This is a very good idea!

**Comment by flyingmachine** [comment]
added by #71
